// GENERATED by tools/generate_sbem_tables.py from
// docs/sbem-descriptor-map.json - do not edit by hand.

#pragma once

#include <cstddef>
#include <cstdint>

// The watch's own field table, as captured from its /Descriptors resource.
// A chunk id in a /Data or /Summary payload is a descriptor id, and a group
// descriptor's payload is its children's values concatenated in order - so
// this table is all a decoder needs. See docs/sbem-chunk-map.md for the
// human-readable version and docs/logbook-data-format.md for how it was
// obtained.
namespace SbemDescriptors {

enum class Format {
    None, Bool, Enum, UInt8, Int8, UInt16, Int16, UInt32, Int32,
    Float32, Float64, Local64, Utf8,
    // Differential formats: the value is a delta against deltaOf's running
    // value rather than a reading of its own.
    DeltaInt8, DeltaUInt8, DeltaInt16,
    // Zero-byte "same as last time" marker.
    Unchanged,
};

struct Descriptor {
    uint16_t id;
    const char *name;       // dotted path, common prefixes stripped; "" for a group
    Format format;
    int8_t size;            // bytes; -1 for utf8 (NUL-terminated), 0 for Unchanged
    double scale;           // value = raw * scale + offset (the schema's <MOD>)
    double offset;
    bool hasNil;            // raw == nil means "no reading"
    double nil;
    uint16_t deltaOf;       // descriptor this is a delta against, 0 if none
    int8_t precision;       // decimal places when written out; -1 = full
    const uint16_t *children;
    uint16_t childCount;    // >0 means this is a group
};

// Returns nullptr for an id the captured table doesn't describe.
const Descriptor *find(uint16_t id);

// The whole built-in table, for code that has to walk it rather than look
// one id up - SbemLayout::resolve() does, because it has to find which
// group carries a field rather than being told.
const Descriptor *all(size_t *count);

} // namespace SbemDescriptors
